# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{things-rb}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Str\303\266m"]
  s.date = %q{2010-01-20}
  s.default_executable = %q{things}
  s.description = %q{Library and command-line tool for accessing Things.app databases}
  s.email = %q{name@my-domain.se}
  s.executables = ["things"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/things",
     "lib/things.rb",
     "lib/things/document.rb",
     "lib/things/focus.rb",
     "lib/things/task.rb",
     "lib/things/version.rb",
     "test/fixtures/Database.xml",
     "test/test_document.rb",
     "test/test_focus.rb",
     "test/test_helper.rb",
     "test/test_task.rb",
     "things-rb.gemspec"
  ]
  s.homepage = %q{http://github.com/haraldmartin/things-rb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Library and command-line tool for accessing Things.app databases}
  s.test_files = [
    "test/test_document.rb",
     "test/test_focus.rb",
     "test/test_helper.rb",
     "test/test_task.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hpricot>, [">= 0"])
    else
      s.add_dependency(%q<hpricot>, [">= 0"])
    end
  else
    s.add_dependency(%q<hpricot>, [">= 0"])
  end
end

